### Get all notifications
GET http://localhost:3000/notifications

### Create a notification
POST http://localhost:3000/notifications
Content-Type: application/json

{
  "recipientId": "{{$guid}}",
  "content": "Você tem uma nova notificação",
  "category": "meta"
}